export const featureEnum = {
  POMODORO_TIMER: "pomodoro-timer",
  FLOATING_TIMER: "floating-timer",
  NEVER_MISS_MEETINGS: "never-miss-meetings",
  TIME_TRACKING: "time-tracking",
  BLOCKING_DISTRACTIONS: "blocking-distractions",
  WORKSPACES: "workspaces",
  AUTO_SETUP: "auto-setup",
  // TASK_MANAGEMENT: "task-management",
  QUICK_ACCESS: "quick-access",
  CLOUD_SYNC: "cloud-sync",
  KEYBOARD_SHORTCUTS: "keyboard-shortcuts",
  ANALYTICS: "analytics",
  COMPACT_MODE: "compact-mode",
  CUSTOM_NOTIFICATIONS: "custom-notifications",
  DAILY_REMINDERS: "daily-reminders",
  APPEARANCE_CUSTOMIZATION: "appearance-customization",
  TASK_RESET: "task-reset",
  FLOATING_BUTTON: "floating-button",
};
